### ISSUE TITLE
Updating README for Golang Beginners

### ISSUE THREAD

**Issue by vipul-dixit-2004** [sunny7899/go-basic#3]
Updating the old README file to help beginners get started with Golang. The new README covers setting up the environment, managing packages, building Go projects, and additional resources for learning Golang all explained in a good manner.
 
![image](https://github.com/user-attachments/assets/179dd167-850d-4614-9e8c-0f12b2fbcd96)
Sample Output

Kindly assign me this issue under Hacktoberfest

**Comment by sunny7899** [comment]
great Go ahead @vipul-dixit-2004
