### ISSUE TITLE
Adding example for math operators

### ISSUE THREAD

**Issue by sanjeevtripurari** [sunny7899/go-basic#8]
Adding example for math operator
```
                1. add
		2. subtract
		3. multiply
		4. divide
```

This takes user input integers does error handling and returns based on user requested operation

**Comment by KaroK365** [comment]
Can you assign it to me and elaborate a bit more? 😊

**Comment by KaroK365** [comment]
I will make a calculator type file which will be performing addition, subtraction, division and multiplication.

**Comment by KaroK365** [comment]
I have made a PR 😊
